// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxGN_-7FVz_OU-C0ndzgfulvAqe4AQ8y4',
    appId: '1:459175381020:web:40b7632b0707d691d937d9',
    messagingSenderId: '459175381020',
    projectId: 'kp-express',
    authDomain: 'kp-express.firebaseapp.com',
    databaseURL: 'https://kp-express-default-rtdb.firebaseio.com',
    storageBucket: 'kp-express.appspot.com',
    measurementId: 'G-SF9EBR6ELG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEPcmJO7LmxhXBqHNU7cK3HcgWCqQEnQs',
    appId: '1:459175381020:android:655f8198c2410527d937d9',
    messagingSenderId: '459175381020',
    projectId: 'kp-express',
    databaseURL: 'https://kp-express-default-rtdb.firebaseio.com',
    storageBucket: 'kp-express.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChmCh_4GpYbp2hTwBmeoqubmjU-pQnlA8',
    appId: '1:459175381020:ios:e59076cb9da9939dd937d9',
    messagingSenderId: '459175381020',
    projectId: 'kp-express',
    databaseURL: 'https://kp-express-default-rtdb.firebaseio.com',
    storageBucket: 'kp-express.appspot.com',
    iosBundleId: 'com.example.kpExpressFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChmCh_4GpYbp2hTwBmeoqubmjU-pQnlA8',
    appId: '1:459175381020:ios:e59076cb9da9939dd937d9',
    messagingSenderId: '459175381020',
    projectId: 'kp-express',
    databaseURL: 'https://kp-express-default-rtdb.firebaseio.com',
    storageBucket: 'kp-express.appspot.com',
    iosBundleId: 'com.example.kpExpressFinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxGN_-7FVz_OU-C0ndzgfulvAqe4AQ8y4',
    appId: '1:459175381020:web:07e4885730c0baabd937d9',
    messagingSenderId: '459175381020',
    projectId: 'kp-express',
    authDomain: 'kp-express.firebaseapp.com',
    databaseURL: 'https://kp-express-default-rtdb.firebaseio.com',
    storageBucket: 'kp-express.appspot.com',
    measurementId: 'G-5FFKXDBDZP',
  );
}
